version: '3'
services:
  mysql:
    container_name: 'mysql'
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: 'zabbix'
      MYSQL_USER: 'zabbix'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_PASSWORD: 'zabbix_pwd'
      MYSQL_ROOT_PASSWORD: 'root_pwd'
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database:/var/lib
      - ./zabbix-data/alertscripts:/usr/lib/zabbix/alertscripts
      - ./zabbix-data/externalscripts:/usr/lib/zabbix/externalscripts
      - ./zabbix-data/export:/var/lib/zabbix/export
      - ./zabbix-data/modules:/var/lib/zabbix/modules
      - ./zabbix-data/enc:/var/lib/zabbix/enc
      - ./zabbix-data/ssh_keys:/var/lib/zabbix/ssh_keys
      - ./zabbix-data/mibs:/var/lib/zabbix/mibs
      - ./zabbix-data/snmptraps:/var/lib/zabbix/snmptraps
    ports:
      - "3306:3306"
    restart: 'on-failure'    
    networks:
      - zabbix-net                                                                                           
  zabbix-server:                                                                                                            
    container_name: 'Zabbix-server'                                                                                         
    image: 'zabbix/zabbix-server-mysql:alpine-5.4-latest'
    environment:
      ZBX_DBTLSCONNECT: 'required'
      DB_SERVER_HOST: 'mysql'                                                                                      
      DB_SERVER_PORT: '3306'                                                                                                 
      MYSQL_USER: 'zabbix'                                                                                               
      MYSQL_PASSWORD: 'zabbix_pwd'                                                                                       
      MYSQL_DATABASE: 'zabbix'
      ZBX_JAVAGATEWAY: 'zabbix-java-gateway'
      MYSQL_ROOT_PASSWORD: 'root_pwd'
    ports: 
      - '10051:10051'                                                                                                       
    networks:
      - zabbix-net
    depends_on:
      - 'mysql'    
  zabbix-web-nginx-mysql:
    container_name: 'zabbix-web-nginx-mysql'
    image: 'zabbix/zabbix-web-nginx-mysql:alpine-5.4-latest'
    environment:
      BX_DB_ENCRYPTION: 'true'
      ZBX_SERVER_HOST: 'zabbix-server'
      ZBX_SERVER_PORT: '10051'
      DB_SERVER_HOST: 'mysql'
      DB_SERVER_PORT: '3306'
      MYSQL_DATABASE: 'zabbix'
      MYSQL_USER: 'zabbix'
      MYSQL_PASSWORD: 'zabbix_pwd'
      MYSQL_ROOT_PASSWORD: 'zabbix_pwd'
      PHP_TZ: 'America/Sao_Paulo'
    depends_on:
      - 'mysql'
      - 'zabbix-server'
    ports:
      - '8080:8080'
    networks:
      - zabbix-net
  zabbix-java-gateway:
    restart: 'unless-stopped'
    image: 'zabbix/zabbix-java-gateway:alpine-5.4-latest'
    depends_on:
      - 'mysql'
    networks:
      - zabbix-net
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - zabbix-net
    links:
      - mysql
      - zabbix-server
    restart: always
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - mysql
      - zabbix-server
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-5.4-latest
    user: root
    networks:
      - zabbix-net
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    depends_on:
      - zabbix-server
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=zabbix-server
networks:
  zabbix-net:
    driver: bridge